server:
  servlet:
    context-path: /api/v1

file:
  upload:
    max-size: 10485760            # 10MB
    max-size-per-file: 104857600  # 100MB
    max-size-in-memory: 0         # all uploaded files are written on disk
#    temp-dir: /usr/local/temp    # don't think I need it

