server:
  servlet:
    context-path: /api/v1

spring:
  servlet:
    multipart:
      max-file-size: 42KB #MB

#file:
#  upload:
#    max-size: 10485760  # 10MB
#    encoding: UTF-8
#    temp-dir: /usr/local/temp    # don't think I need it
